apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  namespace: react-app-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: 908027375897.dkr.ecr.ap-south-1.amazonaws.com/front-end-repo:latest
          ports:
            - containerPort: 80
