apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment  
  namespace: react-app-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app-container
        image: "908027375897.dkr.ecr.ap-south-1.amazonaws.com/front-end-repo:latest"
        ports:
        - containerPort: 80
